apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: k8s-basics
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        access_log off;
        error_log /var/log/nginx/error.log;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_comp_level 4;
        gzip_types text/css application/javascript image/jpeg image/png;

        server {
            listen 80;
            server_name localhost;
            root /var/www/app/public;
            index index.php index.html;

            charset utf-8;

            error_log /var/log/nginx/app-error.log;

            location = /api/health {
                try_files $uri /index.php?$query_string;
            }

            location = /api/ready {
                try_files $uri /index.php?$query_string;
            }

            location ~ \.php$ {
                try_files $uri =404;
                include /etc/nginx/fastcgi.conf;
                fastcgi_pass php-service:9000;
                fastcgi_index index.php;
                fastcgi_param PATH_INFO $fastcgi_path_info;
            }

            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }
        }
    }
