apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: k8s-basics
  labels:
    app: laravel-nginx
spec:
  type: NodePort
  selector:
    app: laravel-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
