apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-job
  namespace: k8s-basics
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U "$POSTGRES_USER"; do
                echo "Waiting for postgres...";
                sleep 2;
              done;
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
      containers:
        - name: migrate
          image: atrem2023/auth-service:amd64
          command: ["bash", "update.sh"]
          env:
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
      restartPolicy: OnFailure
