apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-monitor
  namespace: k8s-basics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-ingress
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - k8s-basics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s